# Generated by Django 4.0.5 on 2022-06-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('petroleum_product', models.CharField(max_length=50)),
                ('sale', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
            ],
        ),
    ]
